### PR TITLE
Fix #12

### LINKED ISSUE #12: Error while compiling in react native v0.51
```
/node_modules/react-native-nested-scroll-view/android/src/main/java/com/rnnestedscrollview/ReactNestedScrollViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:react-native-nested-scroll-view:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-nested-scroll-view:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

How to resolve this?

Thank you

### PR DESCRIPTION
**Pull request by mikeevstropov**

### CODE REVIEW

**Comment by cesardeazevedo** [comment]
Thanks for the contribution, but you based on the `ReactViewGroup.java` and not from `ReactScrollView.java`, they did much more changes on the `ReactScrollView.java`, you can see here https://github.com/facebook/react-native/commit/5180995666051cc047b5828b2b6d45802b1c7b8b

The `getOrCreateReactViewBackground` function was completely removed, and we should the follow the exact `ReactScrollView.java` since it is already a copy from it.

I was just about to push it anyway, but thanks for the contribution.

**Comment by mikeevstropov** [comment]
Ok. Im not a Java developer, but commit was fix an error in #12 So now it works in 0.51. Anyway thank you for amazing library which save my time!
