### ISSUE TITLE
RN 0.51 build error

### ISSUE THREAD

**Issue by odesey** [cesardeazevedo/react-native-nested-scroll-view#24]
I am trying to use this package in my project and get the following error when I run `react-native run android`:

`/node_modules/react-native-nested-scroll-view/android/src/main/java/com/rnnestedscrollview/ReactNestedScrollView.java:308: error: method emitScrollMomentumBeginEvent in class ReactScrollViewHelper cannot be applied to given types;
      ReactScrollViewHelper.emitScrollMomentumBeginEvent(this, 0, velocityY);
                           ^
  required: ViewGroup
  found: ReactNestedScrollView,int,int
  reason: actual and formal argument lists differ in length
1 error
`

Additional info:

`compileSdkVersion 26`
`buildToolsVersion '26.0.2'`

React-Native version: `0.51`

Thanks.

**Comment by cesardeazevedo** [comment]
The last version only works with react-native 0.56.0, upgrade react-native or use an old version of this package.

**Comment by odesey** [comment]
Thanks, using version `6.0.1` fixed the build error.
